v = require ('geometry/vector')
x = v.new(2, 5) + v.new(1,3)
assert(x.x == 3)
assert(x.y == 8)
x = v.new(2, 5) - v.new(1,3)
assert(x.x == 1)
assert(x.y == 2)
x = - v.new(1,3)
assert(x.x == -1)
assert(x.y == -3)
x = v.new(1,3) * 5.5
assert(x.x == 5.5)
assert(x.y == 16.5)
x = 5.5 * v.new(1,3)
assert(x.x == 5.5)
assert(x.y == 16.5)
x = v.new(3,4)
y = v.new()
assert(x:distance(y) == 5.0)
assert(x:nonsqrt_distance(y) == 25)
x = v.new(3,4)
y = v.new(1,2)
assert(x:dot(y) == 11)
